export const investmentPlans = [
  {
    slug: 'debut-plan',
    name: 'Debut Plan',
    minAmount: 50,
    maxAmount: 10000,
    returnPercent: 20,
    dailyInterest: true,
    referralCommissionPercent: 10,
    durationHours: 24,
    durationDays: 1,
    totalReturnPercent: 20,
    capitalIncluded: true,
    description: 'Return 20% daily with capital after 24 hours',
    cta: 'Invest Now',
  },

  {
    slug: 'progressive-package',
    name: 'Progressive Package',
    minAmount: 1500,
    maxAmount: 50000,
    returnPercent: 40,
    dailyInterest: true,
    referralCommissionPercent: 10,
    durationHours: 48,
    durationDays: 2,
    totalReturnPercent: 80,
    capitalIncluded: true,
    description: 'Return 40% daily with capital after 48 hours',
    cta: 'Invest Now',
  },

  {
    slug: 'enhanced-package',
    name: 'Enhanced Package',
    minAmount: 5500,
    maxAmount: 100000,
    returnPercent: 50,
    dailyInterest: true,
    referralCommissionPercent: 10,
    durationHours: 96,
    durationDays: 4,
    totalReturnPercent: 200,
    capitalIncluded: true,
    description: 'Return 50% daily with capital after 96 hours',
    cta: 'Invest Now',
  },

  {
    slug: 'elite-package',
    name: 'Elite Package',
    minAmount: 25000,
    maxAmount: null, // Unlimited
    returnPercent: 70,
    dailyInterest: true,
    referralCommissionPercent: 10,
    durationHours: 168,
    durationDays: 7,
    totalReturnPercent: 490,
    capitalIncluded: true,
    description: 'Return 70% daily with capital after 7 days',
    cta: 'Invest Now',
  },
];

